# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_pastemodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastemodel',
            name='slug',
            field=models.CharField(max_length=30),
        ),
    ]
