# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0004_auto_20161026_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastemodel',
            name='name',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
